---
include:
  - board: aum_left
    shield: nice_view
    shield: settings_reset
    snippet: studio-rpc-usb-uart
  - board: aum_right
    shield: nice_view
    shield: settings_reset
  - board: corne-v4_left
    snippet: studio-rpc-usb-uart
  - board: corne-v4_right

