on: [push, pull_request, workflow_dispatch]

jobs:
 
  build:
    runs-on: ubuntu-latest

    steps:
       - run:
          PROTOC_ZIP=protoc-3.20.1-linux-x86_64.zip
          curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.20.1/$PROTOC_ZIP
          sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
          sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
          rm -f $PROTOC_ZIP
 
  

       - uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
