jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    strategy:
      fail-fast: false
      matrix:
        file-prefix: [pro_micro, blackpill]
    uses: lesshonor/zmk/.github/workflows/build-user-config.yml@fix/use-new-container
